---

- name: Install Update CRON
  template:
    src="percona-mirror.j2"
    dest="{{ mirror_cron_dir }}/percona-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="Percona"
    minute="{{ percona_mirror_cron_minute }}"
    hour="{{ percona_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/percona-mirror"
    disabled="{{ percona_mirror_cron_disabled }}"
